version: '3.5'

services:
  mongodb:
    image: mongo:4.4.4-bionic
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: 4-key-metrics
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - ../config/:/app/mongo/
      - ./mongo-db-data/:/data/
    ports:
      - "27017:27017"
    restart: unless-stopped
    entrypoint: /app/mongo/startup.sh

